;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        cua-delete-region
        mc/insert-numbers-padding
        paredit-forward-delete
        ))

(setq mc/cmds-to-run-once
      '(
        anything-execute-extended-command
        anything-exit-minibuffer
        mouse-set-secondary
        ))
